export enum TASK_STATUS  {
    READY_FOR_DEVELOPMENT = 'READY FOR DEVELOPMENT',
    IN_PROGRESS = 'IN PROGRESS',
    CODE_REVIEW = 'CODE REVIEW',
    READY_FOR_TESTING = 'READY FOR TESTING',
    DONE = 'DONE'
}